YumaPos.Tests.Load.Web/Models/HomeModel.cs
namespace YumaPos.Tests.Load.Web.Models
{
    public class HomeModel
    {
        public int ServersCount { get; set; }
        public int TenantsCount { get; set; }
        public int JobsCount { get; set; }
        public int StoresCount { get; set; }
        public int TerminalsCount { get; set; }
        public int TestTasksCount { get; set; }
        public int ClientsCount { get; set; }
        public int EmployeesCount { get; set; }
    }
}

YumaPos.Tests.Load.Web/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YumaPos.Tests.Load.Server.Data;
using YumaPos.Tests.Load.Server.Data.Helpers;
using YumaPos.Tests.Load.Server.Data.Interfaces;
using YumaPos.Tests.Load.Web.Models;

namespace YumaPos.Tests.Load.Web.Controllers
{
    public class CrudController : Controller
    {
        private readonly LoadTestDbContext _db;
        public CrudController(IEntityContainer entityContainer)
        {
            _db = entityContainer.Context;
        }
        public ActionResult Index(string name)
        {
            DataTable model = null;
            switch (name.ToLowerInvariant())
            {
                case "servers":
                    ViewBag.Title = "Servers";
                    model = _db.Servers.CopyGenericToDataTable();
                    break;
                case "tenants":
                    ViewBag.Title = "Tenants";
                    model = _db.Tenants.CopyGenericToDataTable();
                    break;
                case "stores":
                    ViewBag.Title = "Stores";
                    model = _db.Stores.CopyGenericToDataTable();
                    break;
                case "terminals":
                    ViewBag.Title = "Terminals";
                    model = _db.Terminals.CopyGenericToDataTable();
                    break;
                case "employees":
                    ViewBag.Title = "Employees";
                    model = _db.Employees.CopyGenericToDataTable();
                    break;
                case "testtasks":
                    ViewBag.Title = "TestTasks";
                    model = _db.TestTasks.CopyGenericToDataTable();
                    break;
                case "jobs":
                    ViewBag.Title = "Jobs";
                    model = _db.Jobs.CopyGenericToDataTable();
                    break;
                case "clients":
                    ViewBag.Title = "Clients";
                    model = _db.Clients.CopyGenericToDataTable();
                    break;
            }
            return View(model);
        }

        public ActionResult Edit()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [HttpPost]
        public ActionResult Save(dynamic model)
        {
            ViewBag.Message = "Your contact page.";

            return RedirectToAction("Index");
        }
    }
}

YumaPos.Tests.Load.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YumaPos.Tests.Load.Server.Data;
using YumaPos.Tests.Load.Server.Data.Interfaces;
using YumaPos.Tests.Load.Web.Models;

namespace YumaPos.Tests.Load.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly LoadTestDbContext _db;
        public HomeController(IEntityContainer entityContainer)
        {
            _db = entityContainer.Context;
        }
        public ActionResult Index()
        {
            var model = new HomeModel()
            {
                ServersCount = _db.Servers.Count(),
                TenantsCount = _db.Tenants.Count(),
                JobsCount = _db.Jobs.Count(),
                StoresCount = _db.Stores.Count(),
                TerminalsCount = _db.Terminals.Count(),
                TestTasksCount = _db.TestTasks.Count(),
                ClientsCount = _db.Clients.Count(),
                EmployeesCount = _db.Employees.Count(),
            };
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

YumaPos.Tests.Load.Web/Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using YumaPos.Tests.Load.Server.Data;
using YumaPos.Tests.Load.Server.Data.DataObjects;
using YumaPos.Tests.Load.Server.Data.Helpers;
using YumaPos.Tests.Load.Server.Data.Interfaces;
using YumaPos.Tests.Load.Web.Interfaces;
using YumaPos.Tests.Load.Web.Models;

namespace YumaPos.Tests.Load.Web.Controllers
{
    public class TenantController : Controller
    {
        private readonly ITenantService _tenantService;
        private readonly LoadTestDbContext _db;
        public TenantController(IEntityContainer entityContainer, ITenantService tenantService)
        {
            _tenantService = tenantService;
            _db = entityContainer.Context;
        }
        public ActionResult Index(string name)
        {
            var model = _db.Tenants;
            return View(model);
        }

        public ActionResult Edit(Guid id)
        {
            var tenant = _db.Tenants.Single(p => p.TenantId == id);
            return View(tenant);
        }

        [HttpPost]
        public ActionResult Save(Tenant model)
        {
            ViewBag.Message = "Your contact page.";

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Import(Guid id)
        {
            await _tenantService.Import(id);
            return RedirectToAction("Edit", new {id});
        }
    }
}

YumaPos.Tests.Load.Web/Views/Crud/Edit.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

YumaPos.Tests.Load.Web/Views/Crud/Index.cshtml
@using System.Data
@model DataTable
@{
    Layout = "../Shared/_Layout.cshtml";
}
<style type="text/css">
    table, th, td {
        border: 1px black solid;
        border-collapse: collapse;
        padding: 3px;
    }
</style>
<h2>@ViewBag.Title</h2>
<table >
    <tr>
        @foreach (DataColumn col in Model.Columns)
        {
            <th>@col.ColumnName</th>
        }

    </tr>
    @foreach (DataRow row in Model.Rows)
    {
        <tr>
            @foreach (DataColumn col in Model.Columns)
            {
                <td>@row[col.ColumnName]</td>
            }
        </tr>
    }
</table>

YumaPos.Tests.Load.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

YumaPos.Tests.Load.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

YumaPos.Tests.Load.Web/Views/Home/Index.cshtml
@model YumaPos.Tests.Load.Web.Models.HomeModel
@{
    ViewBag.Title = "Home Page";
}

<style type="text/css">
    table td:last-child {
        text-align: right;
    }
</style>

<div class="row">
    <table>
        <tr>
            <th>Name</th>
            <th>Count</th>
        </tr>
        <tr>
            <td>@Html.ActionLink("Servers", "Index", "Crud", new RouteValueDictionary(){{"name", "Servers" } }, null) Count:</td>
            <td>@Model.ServersCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Tenants", "Index", "Tenant") Count:</td>
            <td>@Model.TenantsCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Stores", "Index", "Crud", new RouteValueDictionary() { { "name", "Stores" } }, null) Count:</td>
            <td>@Model.StoresCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Terminals", "Index", "Crud", new RouteValueDictionary() { { "name", "Terminals" } }, null) Count:</td>
            <td>@Model.TerminalsCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Employees", "Index", "Crud", new RouteValueDictionary(){{"name", "Employees" } }, null) Count:</td>
            <td>@Model.EmployeesCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("TestTasks", "Index", "Crud", new RouteValueDictionary(){{"name", "TestTasks" } }, null) Count:</td>
            <td>@Model.TestTasksCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Jobs", "Index", "Crud", new RouteValueDictionary(){{"name", "Jobs" } }, null) Count:</td>
            <td>@Model.JobsCount</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Clients", "Index", "Crud", new RouteValueDictionary(){{"name", "Clients" } }, null) Count:</td>
            <td>@Model.ClientsCount</td>
        </tr>
    </table>
</div>

YumaPos.Tests.Load.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

YumaPos.Tests.Load.Web/Views/Tenant/Edit.cshtml
@model YumaPos.Tests.Load.Server.Data.DataObjects.Tenant

<h2>Edit tenant @Model.TenantAlias</h2>
@using (@Html.BeginForm("Save"))
{
    @Html.HiddenFor(p => p.TenantId);

    <table>
        <tr><td></td><td></td></tr>
        <tr>
            <td>Alias</td>
            <td>
                @Html.TextBoxFor(p => p.TenantAlias);
            </td>
        </tr>
        <tr>
            <td>Login</td>
            <td>
                @Html.TextBoxFor(p => p.Login);
            </td>
        </tr>
        <tr>
            <td>Password:</td>
            <td>
                @Html.TextBoxFor(p => p.Password);
            </td>
        </tr>
        <tr>
            <td>Job:</td>
            <td>
                @Html.TextBoxFor(p => p.JobId);
            </td>
        </tr>
        <tr>
            <td>Server</td>
            <td>
                @Html.TextBoxFor(p => p.ServerId);
            </td>
        </tr>
        <tr><td></td><td>@Html.ActionLink("Import Employes and terminals", "Import", new {id = Model.TenantId})</td></tr>
        <tr><td></td><td></td></tr>
    </table>
}

YumaPos.Tests.Load.Web/Views/Tenant/Index.cshtml
@model System.Data.Entity.DbSet<YumaPos.Tests.Load.Server.Data.DataObjects.Tenant>

<h2>@ViewBag.Titile</h2>
<table>
    <tr>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.ActionLink(item.TenantAlias, "Edit", new {id = item.TenantId})</td>
        </tr>
    }
</table>